import type { FormData } from './types'

const FIELD_LABELS: Record<string, string> = {
  providerCompany: 'Provider Company',
  providerAddress: 'Provider Address',
  providerContact: 'Provider Contact',
  customerCompany: 'Customer Company',
  customerAddress: 'Customer Address',
  customerContact: 'Customer Contact',
  serviceDescription: 'Service Description',
  termMonths: 'Term (months)',
  startDate: 'Start Date',
  endDate: 'End Date',
  effectiveDate: 'Effective Date',
  fees: 'Fees',
  paymentTerms: 'Payment Terms',
  governingLaw: 'Governing Law',
  jurisdiction: 'Jurisdiction',
  modifications: 'Modifications',
  slaTerms: 'SLA Terms',
  dataHandling: 'Data Handling',
  uptime: 'Uptime Guarantee',
  supportHours: 'Support Hours',
  ipOwnership: 'IP Ownership',
  compensation: 'Compensation',
  timeline: 'Timeline',
  deliverables: 'Deliverables',
  projectScope: 'Project Scope',
}

function labelOf(k: string): string {
  if (FIELD_LABELS[k]) return FIELD_LABELS[k]
  return k.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase()).trim()
}

const PARTY_KEYS = ['providerCompany', 'providerAddress', 'providerContact', 'customerCompany', 'customerAddress', 'customerContact']
const SCOPE_KEYS = ['serviceDescription', 'projectScope', 'deliverables']
const TERM_KEYS = ['startDate', 'endDate', 'effectiveDate', 'termMonths', 'timeline']
const FINANCIAL_KEYS = ['fees', 'paymentTerms', 'compensation']
const LEGAL_KEYS = ['governingLaw', 'jurisdiction', 'modifications', 'slaTerms', 'dataHandling', 'uptime', 'supportHours', 'ipOwnership']

export function fillGenericTemplate(fields: Record<string, unknown>): string {
  const hr = '─'.repeat(72)
  const sectionNames = ['PARTIES', 'SCOPE OF SERVICES', 'TERM & DURATION', 'FINANCIAL TERMS', 'LEGAL PROVISIONS', 'ADDITIONAL TERMS']
  const allKeys = [PARTY_KEYS, SCOPE_KEYS, TERM_KEYS, FINANCIAL_KEYS, LEGAL_KEYS]
  const used = new Set<string>()
  const sections: string[] = []
  let sectionIdx = 0

  for (const keys of allKeys) {
    const lines: string[] = []
    for (const k of keys) {
      const v = fields[k]
      if (v != null && v !== '') {
        lines.push(`  ${labelOf(k).padEnd(28)} ${v}`)
        used.add(k)
      }
    }
    if (lines.length > 0) {
      sections.push(`${sectionNames[sectionIdx]}\n${hr}\n${lines.join('\n')}`)
    }
    sectionIdx++
  }

  const rest: string[] = []
  for (const [k, v] of Object.entries(fields)) {
    if (!used.has(k) && v != null && v !== '') {
      rest.push(`  ${labelOf(k).padEnd(28)} ${v}`)
    }
  }
  if (rest.length > 0) sections.push(`ADDITIONAL TERMS\n${hr}\n${rest.join('\n')}`)

  return `PREPARED BY PRELEGAL
${hr}

LEGAL AGREEMENT
${hr}

This document is a draft legal agreement generated by Prelegal AI based on the information you provided. It should be reviewed by a legal professional before signing.

${sections.join(`\n${hr}\n\n`)}

${hr}

SIGNATURE PAGE
${hr}

By signing below, the parties acknowledge that they have reviewed and agree to the terms outlined in this agreement.

  PARTY 1                                      PARTY 2
  Signature: __________________                Signature: __________________
  Date: __________________                      Date: __________________

${hr}

DISCLAIMER
This document is a draft and has not been reviewed by a legal professional. It is subject to legal review and may require modifications to comply with applicable laws and regulations. Prelegal AI is not a law firm and does not provide legal advice.`
}

export function fillTemplate(d: FormData): string {
  const c = d.party1
  const p = d.party2
  const purpose = d.purpose
  const effectiveDate = d.effectiveDate
  const governingLaw = d.governingLaw
  const jurisdiction = d.jurisdiction

  const hr = '─'.repeat(72)

  return `PREPARED BY PRELEGAL
${hr}

MUTUAL NON-DISCLOSURE AGREEMENT
Cover Page
${hr}

This Mutual Non-Disclosure Agreement (the "MNDA") consists of: (1) this Cover Page and (2) the Common Paper Mutual NDA Standard Terms Version 1.0 ("Standard Terms"). Any modifications of the Standard Terms should be made on the Cover Page, which will control over conflicts with the Standard Terms.

${hr}
AGREEMENT SUMMARY
${hr}

Purpose:              ${purpose}
Effective Date:       ${effectiveDate}
Governing Law:        ${governingLaw}
Jurisdiction:         ${jurisdiction}
MNDA Term:            ${d.mndaTermType === 'expires' ? `Expires ${d.mndaTermYears} year(s) from Effective Date` : 'Continues until terminated'}
Confidentiality Term: ${d.confidentialityType === 'years' ? `${d.confidentialityYears} year(s)` : 'In perpetuity'}
Modifications:        ${d.modifications || 'None'}
${hr}

By signing this Cover Page, each party agrees to enter into this MNDA as of the Effective Date.

${hr}
SIGNATURE PAGE
${hr}

                             PARTY 1                           PARTY 2
                             ───────                           ───────
Signature:                 __________________                __________________
Print Name:                ${(c.name || '__________________').padEnd(34)} ${p.name || '__________________'}
Title:                     ${(c.title || '__________________').padEnd(34)} ${p.title || '__________________'}
Company:                   ${(c.company || '__________________').padEnd(34)} ${p.company || '__________________'}
Notice Address:            ${(c.noticeAddress || '__________________').padEnd(34)} ${p.noticeAddress || '__________________'}
Date:                      ${(c.date || '__________________').padEnd(34)} ${p.date || '__________________'}

${hr}
STANDARD TERMS
${hr}

1. INTRODUCTION.

This Mutual Non-Disclosure Agreement (which incorporates these Standard Terms and the Cover Page) ("MNDA") allows each party ("Disclosing Party") to disclose or make available information in connection with the ${purpose} which (1) the Disclosing Party identifies to the receiving party ("Receiving Party") as "confidential", "proprietary", or the like or (2) should be reasonably understood as confidential or proprietary due to its nature and the circumstances of its disclosure ("Confidential Information"). Each party's Confidential Information also includes the existence and status of the parties' discussions and information on the Cover Page. Confidential Information includes technical or business information, product designs or roadmaps, requirements, pricing, security and compliance documentation, technology, inventions and know-how. To use this MNDA, the parties must complete and sign a cover page incorporating these Standard Terms ("Cover Page"). Each party is identified on the Cover Page and capitalized terms have the meanings given herein or on the Cover Page.

2. USE AND PROTECTION OF CONFIDENTIAL INFORMATION.

The Receiving Party shall: (a) use Confidential Information solely for the ${purpose}; (b) not disclose Confidential Information to third parties without the Disclosing Party's prior written approval, except that the Receiving Party may disclose Confidential Information to its employees, agents, advisors, contractors and other representatives having a reasonable need to know for the ${purpose}, provided these representatives are bound by confidentiality obligations no less protective of the Disclosing Party than the applicable terms in this MNDA and the Receiving Party remains responsible for their compliance with this MNDA; and (c) protect Confidential Information using at least the same protections the Receiving Party uses for its own similar information but no less than a reasonable standard of care.

3. EXCEPTIONS.

The Receiving Party's obligations in this MNDA do not apply to information that it can demonstrate: (a) is or becomes publicly available through no fault of the Receiving Party; (b) it rightfully knew or possessed prior to receipt from the Disclosing Party without confidentiality restrictions; (c) it rightfully obtained from a third party without confidentiality restrictions; or (d) it independently developed without using or referencing the Confidential Information.

4. DISCLOSURES REQUIRED BY LAW.

The Receiving Party may disclose Confidential Information to the extent required by law, regulation or regulatory authority, subpoena or court order, provided (to the extent legally permitted) it provides the Disclosing Party reasonable advance notice of the required disclosure and reasonably cooperates, at the Disclosing Party's expense, with the Disclosing Party's efforts to obtain confidential treatment for the Confidential Information.

5. TERM AND TERMINATION.

This MNDA commences on the ${effectiveDate} and expires at the end of the MNDA Term. Either party may terminate this MNDA for any or no reason upon written notice to the other party. The Receiving Party's obligations relating to Confidential Information will survive for the Term of Confidentiality, despite any expiration or termination of this MNDA.

6. RETURN OR DESTRUCTION OF CONFIDENTIAL INFORMATION.

Upon expiration or termination of this MNDA or upon the Disclosing Party's earlier request, the Receiving Party will: (a) cease using Confidential Information; (b) promptly after the Disclosing Party's written request, destroy all Confidential Information in the Receiving Party's possession or control or return it to the Disclosing Party; and (c) if requested by the Disclosing Party, confirm its compliance with these obligations in writing. As an exception to subsection (b), the Receiving Party may retain Confidential Information in accordance with its standard backup or record retention policies or as required by law, but the terms of this MNDA will continue to apply to the retained Confidential Information.

7. PROPRIETARY RIGHTS.

The Disclosing Party retains all of its intellectual property and other rights in its Confidential Information and its disclosure to the Receiving Party grants no license under such rights.

8. DISCLAIMER.

ALL CONFIDENTIAL INFORMATION IS PROVIDED "AS IS", WITH ALL FAULTS, AND WITHOUT WARRANTIES, INCLUDING THE IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

9. GOVERNING LAW AND JURISDICTION.

This MNDA and all matters relating hereto are governed by, and construed in accordance with, the laws of the State of ${governingLaw}, without regard to the conflict of laws provisions of such ${governingLaw}. Any legal suit, action, or proceeding relating to this MNDA must be instituted in the federal or state courts located in ${jurisdiction}. Each party irrevocably submits to the exclusive jurisdiction of such ${jurisdiction} in any such suit, action, or proceeding.

10. EQUITABLE RELIEF.

A breach of this MNDA may cause irreparable harm for which monetary damages are an insufficient remedy. Upon a breach of this MNDA, the Disclosing Party is entitled to seek appropriate equitable relief, including an injunction, in addition to its other remedies.

11. GENERAL.

Neither party has an obligation under this MNDA to disclose Confidential Information to the other or proceed with any proposed transaction. Neither party may assign this MNDA without the prior written consent of the other party, except that either party may assign this MNDA in connection with a merger, reorganization, acquisition or other transfer of all or substantially all its assets or voting securities. Any assignment in violation of this Section is null and void. This MNDA will bind and inure to the benefit of each party's permitted successors and assigns. Waivers must be signed by the waiving party's authorized representative and cannot be implied from conduct. If any provision of this MNDA is held unenforceable, it will be limited to the minimum extent necessary so the rest of this MNDA remains in effect. This MNDA (including the Cover Page) constitutes the entire agreement of the parties with respect to its subject matter, and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, whether written or oral, regarding such subject matter. This MNDA may only be amended, modified, waived, or supplemented by an agreement in writing signed by both parties. Notices, requests and approvals under this MNDA must be sent in writing to the email or postal addresses on the Cover Page and are deemed delivered on receipt. This MNDA may be executed in counterparts, including electronic copies, each of which is deemed an original and which together form the same agreement.

${hr}

Common Paper Mutual Non-Disclosure Agreement Version 1.0 — Free to use under CC BY 4.0.`
}
